### ISSUE TITLE
Unable to download the dataset

### ISSUE THREAD

**Issue by akansh12** [SerdarHelli/The-Classification-of-Thyroid-Tumors-on-UltraSound-Images-using-Deep-Learning-Methods#1]
Dear author, 
I am unable to download the dataset(cimalab.intec.co/applications/thyroid/thyroid.zip). Please check the download link, also if possible, upload the whole data to google drive and share that link. 

Thanks and regards,
Akansh 
akanshmaurya@gmail.com

**Comment by SerdarHelli** [comment]
Thanks , I check out . Now , it should be correct one. :)
